name: Deploying @bundlejs/mobx npm package
on:
  push:
    branches:
      - master
concurrency: master
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci
      - run: npm run build:prod

      - name: Publish to npm
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          npm publish
